DeviaVir/terraform-provider-gsuite

- Gopkg.lock
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_user.go
- gsuite/utils.go
This attempts to deal with quota errors on high volumes of requests.
> Quotas: deal with quota errors

- Gopkg.lock
- Makefile
- examples/admin-group-member/devteam3.tf
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_user.go
fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/7
Tested locally with success. 🏴
> Importers: group, group member, user

- gsuite/resource_group_member.go
> Added ForceNew to member schema

- Makefile
- README.md
- gsuite/config.go
- gsuite/config_test.go
- gsuite/provider.go
- gsuite/provider_test.go
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_group_members.go
- gsuite/resource_user.go
- main.go
> Limit scope to what we actually use

- Makefile
- gsuite/resource_group_member.go
> Group member notfound fix

- Gopkg.lock
- Makefile
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_group_members.go
- gsuite/resource_user.go
hopefully fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/35#issuecomment-445171967
> Lowercase: attempt #2

- .github/stale.yml
- Makefile
- README.md
- examples/admin-group-member/devteam3.tf
- examples/group-members/team.tf
- gsuite/config.go
- gsuite/provider.go
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_group_members.go
- gsuite/utils.go
- fix #29
- fix #37
- fix #39 
- add stale bot
- tried adding suppressDiff for #35, but looks impossible to fix from the provider side
> Various fixes Dec 2018

- gsuite/resource_domain.go
- gsuite/resource_group.go
- gsuite/resource_group_member.go
- gsuite/resource_group_members.go
- gsuite/resource_user.go
- gsuite/resource_user_schema.go
- gsuite/utils.go
rel to https://github.com/DeviaVir/terraform-provider-gsuite/pull/47
> Add retryNotFound and retry on creation

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
Resolves #50
Contains https://github.com/DeviaVir/terraform-provider-gsuite/pull/52
> Update to terrafrom 0.12

- gsuite/data_user.go
- gsuite/resource_user.go
This is a simple feature to add, requested by others in too.
(https://github.com/DeviaVir/terraform-provider-gsuite/issues/62)
> Adding org_unit_path support for users to GSuite Terraform provider

- gsuite/resource_user.go
@mattsimonsen noticed that updates to the custom schema fields made in the UI were not reflected and/or changed back by terraform.
Turned out we were not reading them in correctly, so terraform was just not comparing the two values.
Resolved in this PR.
> Custom Schema fix

- gsuite/resource_user.go
Alternative to https://github.com/DeviaVir/terraform-provider-gsuite/pull/81 that honors your concerns about "bubbling up" errors. Also addresses a secondary issue with users that have more than one custom schema entry constantly being flagged for an update due to golang map key order randomization.
This should resolve issue #79 
Please let me know if there are any additional concerns with this approach.
> Fix custom resource ordering

- gsuite/resource_user.go
fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/123
@joshua-rutherford mind reviewing?
> fix a bug with checking if a user exists

- gsuite/data_user_attributes.go
> pass type=work to all multi-valued attributes

- examples/user/devteam.tf
- go.mod
- go.sum
- gsuite/resource_user.go
Hello,
I would like to create users, but I don't want to manage password in terraform.
I create this Pull Request to automatically generate a secured password that the user will not know. To log in, the user will need to click on "forget the password?" to generate a new one.
What do you think about this feature ?
Cheers
Romain
> feat: generate a random password at user creation if not defined

- gsuite/data_user.go
- gsuite/resource_user.go
Hi! 
I would like to add a list of organizations the user belongs to 
This PR adds the `organizations` field in the creation of `gsuite_user` resource in case someone wants to provide this info to their gsuite users. 
Regards
Ramiro
> Add a list of organizations the user belongs to

- gsuite/resource_group.go
potential fix for https://github.com/DeviaVir/terraform-provider-gsuite/issues/142
> try to read the group before adding aliases

- Makefile
- README.md
- gsuite/resource_user.go
- website/docs/d/group.md
- website/docs/d/group_settings.md
- website/docs/d/user.md
- website/docs/d/user_attributes.md
- website/docs/index.html.markdown
- website/docs/r/domain.md
- website/docs/r/group.md
- website/docs/r/group_member.md
- website/docs/r/group_members.md
- website/docs/r/group_settings.md
- website/docs/r/user.md
- website/docs/r/user_attributes.md
- website/docs/r/user_schema.md
- website/gsuite.erb
not perfect, but should be complete enough to get started with
> website: init docs

- examples/custom-attributes/custom-attributes.tf
- website/docs/r/user_attributes.md
Update docs on setting gsuite_user_attributes properly
> Fix for https://github.com/DeviaVir/terraform-provider-gsuite/issues/149

- website/docs/r/group_settings.md
- The notation is based on terraform-provider-aws.
- I've copied the comment out listed at the following URL .
- https://github.com/googleapis/google-api-go-client/blob/master/groupssettings/v1/groupssettings-gen.go
- The value of Defaults was obtained from
- https://github.com/DeviaVir/terraform-provider-gsuite/blob/master/gsuite/resource_group_settings.go
#88
> Update website document: r/group_settings.md

- website/docs/d/group.md
- website/docs/d/group_settings.md
- website/docs/d/user.md
- website/docs/r/domain.md
- website/docs/r/group.md
- website/docs/r/group_member.md
- website/docs/r/group_members.md
- website/docs/r/user.md
- website/docs/r/user_schema.md
- The notation is based on terraform-provider-aws.
- I've copied the comment out listed at the following URL .
- https://github.com/googleapis/google-api-go-client/blob/master/admin/directory/v1/admin-gen.go
- https://github.com/googleapis/google-api-go-client/blob/master/groupssettings/v1/groupssettings-gen.go
- The `data source` is described simply because it is a value to be obtained
#88
> Update all documents

- gsuite/resource_group_settings.go
- website/docs/r/group_settings.md
Ref: https://pkg.go.dev/google.golang.org/api/groupssettings/v1#pkg-constants
> feat: support ALL_OWNERS_CAN_CONTACT option for who_can_contact_owner
