gsuite/resource_group_members.go
Fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/6
This adjusts the members resource to first check if an email is a group, and then use different logic for adding groups, or reverts to the current logic.
FYI @psalaberria002
=> Resource group members: allow nesting groups

.travis.yml, Gopkg.lock, Makefile, README.md, gsuite/config.go, gsuite/config_test.go, gsuite/provider.go, gsuite/provider_test.go, gsuite/resource_user.go, gsuite/test-fixtures/fake_account.json, gsuite/utils.go, main.go
It is mostly based on the Google provider.
Additional configurations were taken from https://developers.google.com/admin-sdk/directory/v1/guides/delegation
The optional provider configuration looks like this:
```
provider "gsuite" {
credentials = "${file("./service-account.json")}"
//credentials = "./service-account.json"
impersonated_user_email = "admin@xxx.com"
}
```
=> Make it possible to run as a service account

Makefile
Terraform finds the versions based on the filename.
This way we do not need to rename the file when installing.
See https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
=> Add version to the binaries

Makefile, gsuite/resource_group_members.go
fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/23
If the hasMember check fails, since the member is unknown (or external) we should still allow it to continue.
=> Skip the return on hasMember, immediately create

gsuite/resource_group_member.go
**Summary:**
When adding a member to a group and that member has already been added manually by a group manager, `google.golang.org/api/admin/directory/v1` throws a `Member already exists` error.
**Reproduce:**
* Have a group manager add user `a@b.com` to an existing google group
* Add membership for that user in terraform
```
resource "gsuite_group_member" "some_manager" {
group = "yourgroup@google"
email = "a@b.com"
role  = "MANAGER"
}
```
* terraform apply
**Error Encountered:**
```
* gsuite_group_member.some_manager: 1 error(s) occurred:
* gsuite_group_member.some_manager: error creating group member: googleapi: Error 409: Member already exists., duplicate
```
**Suggested Patch:**
Since the user is not originally managed by terraform, the user is attempted to be created.
* Check if …
=> Group member: add a member that exists from a manual addition

README.md, examples/domain/domain.tf, gsuite/config.go, gsuite/provider.go, gsuite/resource_domain.go, gsuite/utils.go
I added a new resource for domain. The reference Admin SDK Directory API is https://developers.google.com/admin-sdk/directory/v1/reference/domains.
It is now possible to insert/read/delete domains.
I have also added the option to add `customer_id` in the provider configuration.  This would be the G Suite customer ID, which is required for Domains and also other G Suite Admin SDK Directory APIs.
=> Domain resource

gsuite/resource_group_members.go, gsuite/utils.go
I found 3 things that break this resource.
1. `DiffSuppressFunc` seems to break the logic that fetches the members from the config.
2. `ForceNew` on email change makes sense in `gsuite_group_member`, but not here.
3. The retry on 404s slows down the upsertMember function a lot. 404s are expected in https://github.com/DeviaVir/terraform-provider-gsuite/blob/release/0.1.14/gsuite/resource_group_members.go#L259-L261
Removing the 404 from retries may break some other code in other resources.
I originally based the resource on the logic found here: https://github.com/terraform-providers/terraform-provider-google-beta/blob/63f47d34c21f4b29ba024cb9f13e887d9b4a3e55/google-beta/resource_google_project_services.go
They don't have any `DiffSuppressFunc`. The diff indeed looks much cleaner, but we …
=> Fix gsuite_group_members

Makefile, gsuite/data_group.go, gsuite/data_user.go, gsuite/provider.go, gsuite/resource_group.go, gsuite/resource_user.go, gsuite/utils.go
Fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/49
Example:
```
data "gsuite_user" "chase" {
primary_email = "xxx@xxx"
}
data "gsuite_group" "admin_team" {
email = "xxx-team@xxx"
}
output "admin-team" {
value = "${data.gsuite_group.admin_team.member}"
}
output "chase" {
value = "${data.gsuite_user.chase.name}"
}
```
```
Outputs:
admin-team = [
{
email = xxx@xxx,
etag = "xxx",
kind = admin#directory#member,
role = OWNER,
status = ACTIVE,
type = USER
}
]
chase = {
family_name = xxx
full_name = Chase xxx
given_name = Chase
}
```
=> data: group & user

Makefile, gsuite/resource_group_member.go, gsuite/utils.go
reproduced by removing the terraform resource, creating the group member via the console, and trying to terraform apply: the null pointer is because it tries to use `createdGroupMember`'s id, but it doesn't exist, it is in `locatedGroupMember` instead. However, we are setting `Id` so we can just fetch that instead. I also went ahead and added a retryFunc that skips the duplicate check since that is not needed for the group member insert, it would only eat up minutes of your time.
=> bugfix: already existing member bug

gsuite/resource_user.go, gsuite/utils.go
@DeviaVir I found this bug:
When GETing a user right after creating it the response may not have the Name field yet. If you retry, it'll eventually be populated and the terraform run will succeed.
This is most likely because adding the user's name is a separate API call that is run after actually creating the user, you can confirm that by running terraform in debug mode where you'll see:
```
PUT /admin/directory/v1/users/XXXXXXX?alt=json&prettyPrint=false HTTP/1.1
Host: www.googleapis.com
User-Agent: google-api-go-client/0.5 (darwin amd64) Terraform/0.12.2
Content-Length: 75
Content-Type: application/json
Accept-Encoding: gzip
{
"name": {
"familyName": "Some last name",
"givenName": "First Name"
},
"posixAccounts": []
}
```
And the Google admin UI also warns you about this eventual …
=> Eventual consistency

examples/user/devteam.tf, gsuite/resource_user.go
With this the externalIds field of a user can be populated.
https://godoc.org/google.golang.org/api/admin/directory/v1#UserExternalId
Example use case: https://gsuiteupdates.googleblog.com/2018/07/employee-id-login-challenge-g-suite.html
=>  Add external_ids argument

gsuite/resource_group_settings.go
Hey,
The documentation for `whoCanBanUsers` says:
> **Deprecated**. Use the whoCanModerateMembers property instead.
https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups
Now my terraform plan tries to change this all the time.
This is the quick fix that will allow people to continue, though I'm interested to know what your thoughts are on making sure that for the deprecated fields no values are sent unless specified by the user.
=> Add the 'NONE' option to 'who_can_ban_users'

gsuite/resource_group_settings.go
I tried an import of group settings with
`terraform import gsuite_group_settings.gcp-permissions-bender gcp-permissions-bender@mydomain.com`
and Terraform crashed. According to the debug log output the first import step was successful, but in a second step the state was refreshed with `resourceGroupSettingsRead` . This function is using the attribute email as ID (`d.SetId(d.Get("email").(string))`) which was not set by `resourceGroupSettingsImporter` before:
```
...
[0m[1mgsuite_group_settings.gcp-permissions-bender: Refreshing state... [id=gcp-permissions-bender@nomail.rewe-digital.com][0m
2019-09-23T10:27:25.137+0200 [DEBUG] plugin.terraform-provider-gsuite: ---[ REQUEST ]---------------------------------------
2019-09-23T10:27:25.137+0200 [DEBUG] plugin.terraform-provider-gsuite: …
```
=> Group Settings Import: email attribute needed to prevent crash in subsequent state refresh

gsuite/resource_user.go
L241,249:  Set recovery_email and recovery_phone to Optional
L352:  Fixed logic where resource was attempting to set user.RecoveryEmail to value from recovery_phone
=> Fixes to resource_user.go

Makefile, gsuite/utils.go
This is a change that implements exponential backoff as described here https://developers.google.com/admin-sdk/directory/v1/limits
Especially helpful when using this provider at large scale and hitting quotas or bugs in the API.
=> API backoff

Makefile, gsuite/config.go, gsuite/data_group.go, gsuite/data_user.go, gsuite/provider.go, gsuite/resource_domain.go, gsuite/resource_group.go, gsuite/resource_group_member.go, gsuite/resource_group_members.go, gsuite/resource_group_settings.go, gsuite/resource_user.go, gsuite/resource_user_schema.go, gsuite/utils.go
This should allow us to customize the time the provider backs off for quota issues.
Also replaced some `retry`'s with `retryNotFound` for https://github.com/DeviaVir/terraform-provider-gsuite/issues/90
=> Allow customizing timeouts

gsuite/data_group_settings.go, gsuite/resource_group_settings.go
Will result in slightly better errors:
> Error: [ERROR] Error updating group settings for 'group@domain.com': googleapi: Error 400: Invalid Value, invalid
Pointing you to the group causing a problem
=> Add mention of the group email when an error occurs

examples/user/devteam.tf, gsuite/resource_user.go, gsuite/utils.go
Any interest in bringing in a `gsuite_user_aliases` resource for managing aliases.  I took the route of making it a separate resource instead of nesting multiple api calls within the existing `gsuite_user` resource as the alias updates are independent of the user updates.
=> add user aliases resource

examples/user/devteam.tf, gsuite/resource_user.go
This is based on #120 so that should be merged first, but this simply makes it so the user's password and hash function are fully ignored after creation.
Expected usage is now:
```
resource "random_password" "keyser_soze" {
length = 16
special = true
}
resource "gsuite_user" "keyser_soze" {
...
password = random_password.keyser_soze.result
}
```
or (following recommended best practices):
```
resource "random_password" "keyser_soze" {
length = 16
special = true
}
resource "gsuite_user" "keyser_soze" {
...
hash_function = "md5"
password = md5(random_password.keyser_soze.result)
}
```
=> allow passwords only on creation

examples/user/devteam.tf, gsuite/config.go, gsuite/provider.go, gsuite/resource_user.go
@DeviaVir, fairly straight forward change to prevent the same user getting imported as multiple terraform resources by accident.  This does change the behavior on initial creations (i.e., no longer imports so you'll have to explicitly import existing users).
=> remove update from creation

gsuite/resource_group.go, gsuite/resource_group_member.go, gsuite/resource_group_members.go, gsuite/resource_group_settings.go, gsuite/utils.go, gsuite/utils_test.go
Provisioning gsuite groups with long names returns errors an apply from the API, but it'd be nice to be able to catch the errors a little earlier such as during a terraform plan and provide some more meaningful errors.
Sample resource
```
resource "gsuite_group" "long_group" {
description = "Testing generation of a group with too long of an email"
email       = "really-really-really-really-really-really-really-long-name-here@domain.com"
name        = "groupname"
}
```
I think there is a length restriction to the group name as well but didn't find any info on it with a little searching.  Might be useful to add later.
Error thrown on a tf plan
```
Error: local portion of email really-really-really-really-really-really-really-long-name-here@domain.com exceeds 63 characters
on main.tf line 2, …
```
=> validate that the local portion of the group email doesn't exceed 63 characters

examples/custom-attributes/custom-attributes.tf, gsuite/provider.go, gsuite/resource_user_attributes.go, gsuite/resource_user_fields.go
This PR adds the `gsuite_user_attributes` resource, which allows managing a user's custom attributes in custom schemas without having to manage the user itself. Useful when user provisioning is done outside of Terraform.
=> Add gsuite_user_attributes resource

README.md
Hello,
This PR fix the following error when using resource "gsuite_group_settings"
www-Authenticate: Bearer realm="https://accounts.google.com/", error=insufficient_scope, scope="https://www.googleapis.com/auth/apps.groups.settings"
=> Add reference about scope apps.groups.settings

gsuite/utils.go, gsuite/utils_test.go
Ran into a case where a non-email address is supplied to the `validateEmail` function.
```
2020-08-19T00:23:04.610Z [DEBUG] plugin.terraform-provider-gsuite_v0.1.54: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe0d055]
2020-08-19T00:23:04.610Z [DEBUG] plugin.terraform-provider-gsuite_v0.1.54: 
2020-08-19T00:23:04.610Z [DEBUG] plugin.terraform-provider-gsuite_v0.1.54: goroutine 2535 [running]:
2020-08-19T00:23:04.610Z [DEBUG] plugin.terraform-provider-gsuite_v0.1.54: github.com/DeviaVir/terraform-provider-gsuite/gsuite.validateEmail(0xeb9fa0, 0xc00031f810, 0x1090b3e, 0x5, 0x0, 0x0, 0x4b90dd, 0xf10660, 0xc00031f390, 0x94)
2020-08-19T00:23:04.610Z [DEBUG] plugin.terraform-provider-gsuite_v0.1.54: 	/go/src/github.com/DeviaVir/terraform-provider-gsuite/gsuite/utils.go:192 …
```
=> catch the case where an non-email is provided

website/docs/d/group.md
While not explicitly doc'ed `id` was available from the data resource for `group`. Explicitly adding it to the docs in case others like myself don't think to try `id` since it wasn't doced. Closes #155
=> Add Note that Group ID is Available Attribute

gsuite/resource_group_members.go
We had a case where the API had some users with the MEMBER role, but the Terraform config was trying to set the OWNER role to them.
We got `Error: [ERROR] Error updating memberships: [ERROR] Error updating groupMember (x@x.com): nested groups should be role MEMBER` which made no sense.
Is there any reason for that condition to be in the reconcile function?
=> Remove a block which failed with the wrong error

Makefile
Fixes https://github.com/DeviaVir/terraform-provider-gsuite/issues/167
=> Add arm64 to makefile and use golang 1.16 for cross compiling arm64

gsuite/resource_user_attributes.go
Hey,
This pull request introduces a fix for an issue [#173](https://github.com/DeviaVir/terraform-provider-gsuite/issues/173), when a deleted user attributes were not cleaned from the GSuite.
The fix is basically a change of a `UsersService.Patch` method to `UsersService.Update`.
SDK documentation for [`Patch`](https://pkg.go.dev/google.golang.org/api@v0.44.0/admin/directory/v1#UsersService.Patch) describes the following:
> Patch: Updates a user using patch semantics. The update method should be used instead, since it also supports patch semantics and has better performance. This method is unable to clear fields that contain repeated objects (`addresses`, `phones`, etc). Use the update method instead.
SDK documentation for [`Update`](https://pkg.go.dev/google.golang.org/api@v0.44.0/admin/d …
=> Fix user attributes deletion issue

gsuite/config.go, website/docs/index.html.markdown
Bugfix for changes introduces in https://github.com/DeviaVir/terraform-provider-gsuite/pull/171
```
go test -i ./... || exit 1
go test: -i flag is deprecated
echo ./... | \
xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 ./...
?   	github.com/DeviaVir/terraform-provider-gsuite	[no test files]
ok  	github.com/DeviaVir/terraform-provider-gsuite/gsuite	0.360s
```
If metadata endpoint is blocked or email is not configured properly, the following error will show (this is not an error with the code, but a config error):
```
Error: [ERROR] Error creating group: Post "https://admin.googleapis.com/admin/directory/v1/groups?alt=json&prettyPrint=false": impersonate: status code 400: {
"error": {
"code": 400,
"message": "Request contains an invalid argument.", …
```
=> [bugfix] Don't use httpclient unless it is set
